name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Or the branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      # Add more steps as needed for build, test, etc.

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /projects/BioSecureCert
            git pull origin main  # or specific branch
            npm install
            pm2 restart  BioSecureCert
